spring:
  cloud:
    gateway:
      routes:
        - id: components-route
          uri: ${JPA_APP_URI:http://localhost:8082}
          predicates:
            - Path=/spaceshipComponents/**
        - id: spaceships-route
          uri: ${JPA_APP_URI:http://localhost:8082}
          predicates:
            - Path=/spaceships/**
        - id: spaceship-image-route
          uri: ${MONGO_APP_URI:http://localhost:8081}
          predicates:
            - Path=/images/**
          filters:
            - PrefixPath=/api